# -*- coding: utf-8 -*-
#
# ESCSconf documentation build configuration file, created by
# sphinx-quickstart on Tue Sep 17 16:38:44 2013.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os


# -- General configuration ------------------------------------------------

needs_sphinx = '1.2'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'ESCS NOTO setup and configuration'
copyright = u'2016, Marco Bartolini, Andrea Orlati'
#
# The short X.Y version.
version = 'escs 0.6'
# The full version, including alpha/beta/rc tags.
release = '0.6'

exclude_patterns = []

pygments_style = 'sphinx'


# -- Options for HTML output ----------------------------------------------

# Use the custom shinx_rtd_theme (readthedocs.org)
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
html_theme_path = ['theme']
if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path.append(sphinx_rtd_theme.get_html_theme_path())
    # Override default css to get a larger width for local build                 
    def setup(app):                                                              
        # app.add_javascript("custom.js")                                         
        app.add_stylesheet('pygments.css')                                
else:                                                                            
    # Override default css to get a larger width for ReadTheDoc build            
    html_context = {                                                             
        'css_files': [                                                           
            'https://media.readthedocs.org/css/sphinx_rtd_theme.css',            
            'https://media.readthedocs.org/css/readthedocs-doc-embed.css',       
            '_static/pygments.css',                                       
        ],                                                                       
    }

# Short title used e.g. for <title> HTML tags.
html_short_title = 'DISCOS@NOTO configuration'

# Path to find HTML templates.
templates_path = ['theme/templates']
# Additional static files.
#html_static_path = ['theme/static/']

# Custom sidebar templates, filenames relative to this file.
#html_sidebars = {}

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Output file base name for HTML help builder.
htmlhelp_basename = 'discos-noto'

#html_static_path = ['static/escsconf/']

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': 'Rapporto Interno IRA 01/14',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'DISCOSconf.tex', u'DISCOS NOTO 0.2',
   u'Marco Bartolini, Andrea Orlati', 'howto'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
#latex_show_urls = True

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = False


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'discosconf', u'NOTO 0.2',
     [u'Marco Bartolini, Andrea Orlati'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'NOTO DISCOS configuration', u'NOTO DISCOS Configuration',
   u'Marco Bartolini, Andrea Orlati', 'NOTO DISCOS configuration', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False
